name: "Hello CIno"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME: Lakshita
    description: "life"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
